language: android
jdk:
  - oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a
android:
  components:
# Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    #- sys-img-armeabi-v7a-android-17
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
licenses:
  - android-sdk-license-.+
  - '.+'
script:
  - ./gradlew -I init.gradle build